server:
  port: 10001
spring:
  application:
    name: redis-demo
# 单机 Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      # 连接池相关配置
      pool:
        max-active: 8   # 最大连接数（根据并发估算）
        max-idle: 8     # 最大空闲数
        min-idle: 0     # 最小空闲数
    database: 1
# Redis 集群
#  redis:
#    cluster:
#      nodes:
#      - 192.168.100.100:7001
#      - 192.168.100.100:7002
#      - 192.168.100.100:7003
#      - 192.168.100.100:7004
#      - 192.168.100.100:7005
#      - 192.168.100.100:7006